name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          cache: true

      - name: Get Dependencies
        run: flutter pub get

      - name: Re-create Android files from scratch
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.example

      - name: Fix SDK 35 & Kotlin version requirement
        run: |
          sed -i 's/compileSdk = .*/compileSdk = 35/' android/app/build.gradle
          sed -i 's/compileSdkVersion .*/compileSdkVersion 35/' android/app/build.gradle
          sed -i 's/id "org.jetbrains.kotlin.android" version .*/id "org.jetbrains.kotlin.android" version "1.9.20" apply false/' android/settings.gradle

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
